{
 "title": "Cache",
 "description": "Application level metrics related to cache management",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "AVS by index - Quandopasso",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(index)(avs{domain=\"quandopasso\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "AVS by index",
   "type": "timeseries",
   "description": "AVS stored in cache by index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(index)(avs{domain=\"quandopasso\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "AVS by domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum by(domain)(avs)", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Invalid AVS",
   "type": "timeseries",
   "description": "AVS marked as invalid by the cache manager",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(field_in_error)(invalid_avs)",
     "legendFormat": "{{field_in_error}}"
    }
   ]
  },
  {
   "title": "Cache operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "delta(cache_updates[1m])" }
   ]
  }
 ]
}