apiVersion: v1
kind: Pod
metadata:
  name: openssh-server
  namespace: quandopasso
spec:
  # volumes:
  # - ./sshtunnel/data/:/data/:ro
  containers:
    - name: test
      # image: nowsci/sshtunnel
      image: lscr.io/linuxserver/openssh-server:latest
      env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "Etc/UTC"
      - name: USER_PASSWORD
        value: "nonlasai"
      - name: USER_NAME
        value: "quandopasso"
      - name: PASSWORD_ACCESS
        value: "true"
      - name: SUDO_ACCESS
        value: "true"
      - name: DOCKER_MODS
        value: "linuxserver/mods:openssh-server-ssh-tunnel"
      ports:
      - containerPort: 2222


      
