{
 "title": "HTTP",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "HTTP REQUESTS rate (1m)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{route !=\"/liveness\", route !=\"/v2/liveness\"}[1m])",
     "legendFormat": "{{job}} - {{route}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{route !=\"/liveness\", route !=\"/v2/liveness\"}[5m])) by (container) / sum(rate(http_request_duration_seconds_count{route !=\"/liveness\", route !=\"/v2/liveness\"}[5m])) by (container)",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "Requests rate ",
   "type": "timeseries",
   "description": "Rate of received requests (1 minute) for specific services",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{route !=\"/v2/liveness\",route !=\"/liveness\"}[1m])",
     "legendFormat": "{{job}} - {{route}}"
    }
   ]
  }
 ]
}