{
 "title": "Quandopasso cloud services readyness",
 "description": "Quandopasso cloud readyness ",
 "tags": [
  "readyness",
  "mobile-api",
  "cache"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rabbitmq readyness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"common\",container=\"rabbitmq\"}",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "cache readyness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"quandopasso\",container=\"cache\"}",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "mobile API readyness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"quandopasso\",container=\"mobile-api\"}",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "Terminals API readyness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"quandopasso\",container=\"terminals-api\"}",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "Wellknown API readyness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"quandopasso\",container=\"wellknown-api\"}",
     "legendFormat": "ready"
    }
   ]
  }
 ]
}