{
 "title": "Azure Applictaion Gateway",
 "description": "Azure Applictaion Gataway WAF v2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "ResourceGroup", "query": "ResourceGroups()" },
   { "name": "Namespace", "label": "Namespace", "query": "Namespaces($ResourceGroup)" },
   {
    "name": "ResourceName",
    "query": "ResourceNames($ResourceGroup,$Namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Compute Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": null,
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "ComputeUnits",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:557", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:558", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:559", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:560", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:561", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:562", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:563", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:564", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:565", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Current Capacity Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": null,
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "CapacityUnits",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:583", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:584", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:585", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:586", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:587", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:588", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:589", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:590", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:591", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "HealthyHostCount",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:609", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:610", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:611", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:612", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:613", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:614", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:615", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:616", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:617", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Client TLS Protocol",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Listener", "value": "Listener" },
       { "text": "TLS Protocol", "value": "TlsProtocol" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TlsProtocol",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:638", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:639", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:640", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:641", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:642", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:643", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:644", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:645", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:646", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TotalRequests",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:724", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:725", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:726", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:727", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:728", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:729", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:730", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:731", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:732", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TotalRequests",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:531", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:532", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:533", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:534", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:535", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:536", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:537", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:538", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:539", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "New Connections per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": null,
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "NewConnectionsPerSecond",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:801", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:802", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:803", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:804", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:805", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:806", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:807", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:808", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:809", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "Throughput",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:878", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:879", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:880", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:881", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:882", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:883", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:884", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:885", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:886", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Client RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "ClientRtt",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1023", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1024", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1025", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1026", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1027", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1028", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1029", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1030", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1031", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3239", "text": "None", "value": "None" },
       { "$$hashKey": "object:3240", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3241", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3242", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3243", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendConnectTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3230", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3231", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3232", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3233", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3234", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3235", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3236", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3237", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3238", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3279", "text": "None", "value": "None" },
       { "$$hashKey": "object:3280", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3281", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3282", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3283", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendFirstByteResponseTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3270", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3271", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3272", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3273", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3274", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3275", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3276", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3277", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3278", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3315", "text": "None", "value": "None" },
       { "$$hashKey": "object:3316", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3317", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3318", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3319", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3306", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3307", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3308", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3309", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3310", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3311", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3312", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3313", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3314", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "Networking Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BytesSent",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1114", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1115", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1116", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1117", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1118", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1119", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1120", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1121", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1122", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BytesReceived",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "aag-quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1132", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1133", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1134", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1135", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1136", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1137", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1138", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1139", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1140", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "WAF ALL Logs",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics \r\n| where  ResourceProvider == \"MICROSOFT.NETWORK\" and Category == \"ApplicationGatewayFirewallLog\" and action_s == \"Blocked\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| order by TimeGenerated asc",
      "resultFormat": "table",
      "workspace": "98743fe4-f577-4d4f-975d-b7579cfe840e"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "WAF Block Count from IPs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceProvider == \"MICROSOFT.NETWORK\" and Category == \"ApplicationGatewayFirewallLog\"\r and action_s == \"Blocked\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| summarize count() by clientIp_s, bin(TimeGenerated, $__interval)\n",
      "resultFormat": "time_series",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "Rules Current percentage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceProvider == \"MICROSOFT.NETWORK\" and Category == \"ApplicationGatewayFirewallLog\"\r \n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| summarize Count=count() by details_file_s, bin(TimeGenerated, $__interval)",
      "resultFormat": "time_series",
      "workspace": "98743fe4-f577-4d4f-975d-b7579cfe840e"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Block List",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceProvider == \"MICROSOFT.NETWORK\" and Category == \"ApplicationGatewayFirewallLog\"\r and action_s == \"Blocked\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| project TimeGenerated, clientIp_s, requestUri_s, details_file_s",
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  }
 ]
}