{
 "title": "Azure Managed Cluster",
 "description": "https://github.com/yesoreyeram/grafana-azure-dashboards",
 "tags": [
  "azure",
  "templates"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "label": "VM",
    "query": "ResourceNames($ResourceGroup,Microsoft.Compute/virtualMachines)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "98743fe4-f577-4d4f-975d-b7579cfe840e"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "alias": "CPU Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2085", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2086", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2087", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2088", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2089", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2090", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2091", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2092", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "MilliCores" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "98743fe4-f577-4d4f-975d-b7579cfe840e"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "alias": "CPU Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_cpu_usage_millicores",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2226", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2227", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2228", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2229", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2230", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2231", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2232", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2233", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Network In ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_network_in_bytes",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2298", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2299", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2300", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2301", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2302", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2303", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2304", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2305", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_network_out_bytes",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2370", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2371", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2372", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2373", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2374", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2375", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2376", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2377", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Network In bytes vs Network Out bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "alias": "Network in total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_network_in_bytes",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2627", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2628", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2629", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2630", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2631", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2632", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2633", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2634", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "alias": "Network out total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_network_out_bytes",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2635", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2636", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2637", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2638", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2639", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2640", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2641", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2642", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Disk Read Bytes vs Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Average",
      "alias": "Disk Read Bytes",
      "allowedTimeGrainsMs": [
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "cluster_autoscaler_cluster_safe_to_autoscale",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2797", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2798", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2799", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2800", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2801", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2802", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2803", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Disk Write Bytes",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Disk Write Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2738", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2739", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2740", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2741", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2742", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2743", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2744", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2745", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2746", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Disk Used Bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" },
       { "text": "Name of the device", "value": "device" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_disk_usage_bytes",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2442", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2443", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2444", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2445", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2446", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2447", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2448", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2449", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Disk Used Percentage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Name of the node", "value": "node" },
       { "text": "Name of the nodepool", "value": "nodepool" },
       { "text": "Name of the device", "value": "device" }
      ],
      "metricDefinition": "Microsoft.ContainerService/managedClusters",
      "metricName": "node_disk_usage_percentage",
      "metricNamespace": "Microsoft.ContainerService/managedClusters",
      "resourceGroup": "quandopasso_development1",
      "resourceName": "quandopasso-development1",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2514", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2515", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2516", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2517", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2518", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2519", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2520", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2521", "text": "12 hours", "value": "PT12H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "8a0bdc85-cc1c-4894-9acd-aedeec5a3eaa"
    }
   ]
  },
  {
   "title": "Inbound Flows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Inbound Flows",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Outbound Flows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Outbound Flows",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Disk Read Operations/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Disk Read Operations/Sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Disk Write Operations/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Disk Write Operations/Sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "OS disk - Read / Write bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "dimension": null,
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "OS Disk Read Bytes/sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "dimension": null,
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "OS Disk Write Bytes/sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Data disk - Read / Write bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "LUN", "value": "LUN" }
      ],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Data Disk Read Bytes/sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "aeaf6b59-752c-4eb5-bf6b-23765ce37a4b"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "LUN", "value": "LUN" }
      ],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Data Disk Write Bytes/sec",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}