# Default values for vsign persistence POD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ${namespace}

replicaCount: 1
  
environment: ${environment}

storageSize: ${storagesize}
storageClass: ${storageclass}

rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
      

portName: "persistencemetricport"
serviceMonitorRelease: 'observability'
