{
 "title": "Viasuisse import",
 "description": "Measurements from Viasuisse import process",
 "tags": [
  "importer",
  "viasuisse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Importer elapsed time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "importElapsedTime{exported_job=\"importer_adapter\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Events vs Vsigns",
   "type": "stat",
   "description": "Events and visgns generated high level view",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(events{exported_job=\"importer_adapter\"})",
     "legendFormat": "Imported events"
    },
    {
     "expr": "vsigns{category=\"total\", exported_job=\"importer_adapter\"}",
     "legendFormat": "Vsigns from events"
    },
    {
     "expr": "atcc_vsigns{type=\"before_junction\"}",
     "legendFormat": "A-TCC vsigns"
    }
   ]
  },
  {
   "title": "Events filtered out",
   "type": "stat",
   "description": "Counters of events got from Viasuisse that have been filtered out for some reason",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "filteredout{exported_job=\"importer_adapter\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Events directionality",
   "type": "stat",
   "description": "Events with direction information",
   "gridPos": { "h": 9, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_directionality", "legendFormat": "{{directionalityInfo}}" }
   ]
  },
  {
   "title": "Languages in events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (language) (events))",
     "legendFormat": "Available languages"
    }
   ]
  },
  {
   "title": "Events by road",
   "type": "graph",
   "description": "Events imported from Viasuisse grouped by road",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roads{exported_job=\"importer_adapter\"}",
     "legendFormat": "{{road}}"
    }
   ]
  },
  {
   "title": "Events by language",
   "type": "graph",
   "description": "Events imported by Viasuisse grouped by language",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events{exported_job=\"importer_adapter\"}",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Vsigns activity",
   "type": "graph",
   "description": "Changes on the vsigns status. Exported by the persistance service",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "num" } },
   "yaxes": [
    { "format": "num" }
   ],
   "targets": [
    { "expr": "vsigns_activity{}", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Route with no geo info (max in 1 week)",
   "type": "bargauge",
   "description": "Number of events with rouad info for wich we do not have route geo info, grouped by road. The graph shows tha max of last week",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(no_path_for_route[1w])",
     "legendFormat": "{{road}}"
    }
   ]
  },
  {
   "title": "Route with no geo info (count in 1 week)",
   "type": "bargauge",
   "description": "Number of events with road info for which we do not have route geo info, grouped by road.  Total number of times this happen in an import.",
   "gridPos": { "h": 18, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(no_path_for_route[1w])",
     "legendFormat": "{{road}}"
    }
   ]
  },
  {
   "title": "Events received by category",
   "type": "graph",
   "description": "Events downloaded by Viasuisse APIs",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "categories{exported_job=\"importer_adapter\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "ATCC vsigns",
   "type": "graph",
   "description": "Vsigns added by ATCC",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "atcc_vsigns", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Importer elaboration time",
   "type": "timeseries",
   "description": "Elapsed time for inporting events from Viasuisse",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "importElapsedTime{exported_job=\"importer_adapter\"}",
     "legendFormat": "Elapsed time"
    }
   ]
  }
 ]
}