apiVersion: v1
kind: Pod
metadata:
  name: openssh-server
  namespace: quandopasso
spec:
  volumes:
    - name: kube-api-access-2pcjw
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: test
      image: lscr.io/linuxserver/openssh-server:latest
      ports:
        - containerPort: 2222
          protocol: TCP
      env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: Etc/UTC
        - name: USER_PASSWORD
          value: nonlasai
        - name: USER_NAME
          value: quandopasso
        - name: PASSWORD_ACCESS
          value: 'true'
        - name: SUDO_ACCESS
          value: 'true'
        - name: DOCKER_MODS
          value: linuxserver/mods:openssh-server-ssh-tunnel
      resources: {}
      volumeMounts:
        - name: kube-api-access-2pcjw
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  